//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holistic_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_information
    {
        public int id { get; set; }
        public string username { get; set; }
        public string passwordd { get; set; }
        public Nullable<int> age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> phonenumber { get; set; }
        public string city { get; set; }
    }
}
